---
title: "Stat 156 Final Project Part 3: Replicating the Robustness Chekcs"
author: "Ritvik Iyer and Samuel Gao"
date: "11/12/2021"
output: pdf_document
header-includes:
  - \usepackage{booktabs}
  - \usepackage[utf8]{inputenc}
  - \usepackage{setspace}
  - \usepackage{graphicx}
  - \usepackage{rotating}
  - \usepackage{lipsum}
  - \usepackage{adjustbox}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Section 1: Summary of Methodology   

In the paper, the author used two refutation methods to check for the robustness of the results- random common cause (RCC) and placebo treatment (PT). The random common cause treatment adds an independent noise variable as a covariate to the data set and tests the causal effects of the data set. If the relationship is indeed causal, the results stemmed from the treatment should still be relatively stable. Under the placebo treatment test, the tested treatment variable is replaced by noise values instead of the original value, and a causal relationship is estimated again. The effects estimated under the placebo treatment should be 0 instead of the original values.

With the above testing methods, the author utilized four refutation criterions. The first criterion is for the treatment variable to pass both the placebo treatmment test and the RCC test. More specifically, in order for a treatment variable to be considered "passed", its deviation from the original estimated value under the RCC test must be under 10% and results under the placebo treatment test must not be significantly different from 0. If both of these tests are passed, then additional three criterions were established by the authors to further enhance the robustness checks. The other three criterions are thresholds under the RCC test, where the deviations are set at 5%, 1% and 0.5% of the original value, indicating increasing strictness of the test. The authors mandate that a treatment variable pass all four levels of robustness checks in order for a treatment varaible to be considered robust enough.

Under the above-mentioned refutation methods, the wide majority of the estimated treatment variables were refuted by the authors. Looking at the different air pollution factors, PM10 in the cluster 3 spreading phase passed the 1% threshold refutation with a positive ATE value but did not pass the final refutation. For PM2.5, two potential causal effects- one for cluster 2 overall and a second one for cluster 2 during the postpeak phase both did not pass the 1% refutation test. In terms of CO, the cluster 3 postpeak phase passed the initial refutation test but failed at the 5% threshold test, while the SO2 treatment for cluster 3 spreading phase passed the initial and 5% refutation tests but failed at the 1% threshold level. Analyzing meteorological relationship, most of the relationships failed at the 5% level of refutation which indicated that they are most likely insignificant from the authors' perspective. However, one result did pass all of the refutation level tests- air temperature in the cluster 2 spreading phase. This causal effect passed the final refutation test with a causal effect of 0.041, which approximately indicates that given a 1 degree Celcius increase in temperature, this effect increases the newly confirmed cases for cluster 2 during the spreading phase by 0.183 after adjusting for the normalizations. However the authors do note that the final RCC refutation test was passed by 0.00498, which is very cluse to the threshold of 0.005. The authors finally comments that though this causal relationship cannot be ruled out, it can be generally said that from their analysis, enviornmental factors did not generally have an exacerbation impact on the COVID-19  pandemic in the selected Chinese cities during the period selected. 

However, the authors were not very clear in exactly how they selected the treatment effect estimations. They did not state in their paper how they determined whether a relationship was linear or nonlinear, but rather simply reported the results as one or the other. In addition, the authors failed to report any methods they used to see if the results are statistically significant or not. The authors also seemed to only use positive results, in the ATE, for which they did not explicitly explain why.

# Section 2: Replication of Results




\newpage 
# Figures 

\newpage

\begin{table}[ht]
\centering
 \resizebox{0.62\textwidth}{!}{%
\small
\begin{tabular}{rllllllll}
  \hline
 & City\_Cluster\&Pandemic\_Phase & Feature & 0.1\_Level & 0.05\_Level & 0.01\_Level & 0.005\_Level & Final \\ 
  \hline
1 & Cluster 1 Overall & PRES & P & P & F & F &  &  \\ 
  2 &  & TEMP & P & P & P & P & P &  \\ 
  3 &  & HUM & P & P & F & F &  &  \\ 
  4 &  & WSPD & P & P & F & F &  &  \\ 
  5 &  & NO2 & P & P & P & P & P &  \\ 
  6 &  & O3 & P & P & P & P & P &  \\ 
  7 &  & PM2.5 & P & P & P & F &  &  \\ 
  8 &  & PM10 & P & P & P & P & P &  \\ 
  9 &  & SO2 & P & P & P & P & P &  \\ 
  10 &  & CO & P & P & F & F &  &  \\ 
  11 & Cluster 1 Spreading & PRES & P & F & F & F &  &  \\ 
  12 &  & TEMP & F & F & F & F &  &  \\ 
  13 &  & HUM & P & P & F & F &  &  \\ 
  14 &  & WSPD & P & P & P & F &  &  \\ 
  15 &  & NO2 & P & P & P & F &  &  \\ 
  16 &  & O3 & P & P & F & F &  &  \\ 
  17 &  & PM2.5 & P & P & F & F &  &  \\ 
  18 &  & PM10 & P & P & F & F &  &  \\ 
  19 &  & SO2 & P & P & P & P & P &  \\ 
  20 &  & CO & P & F & F & F &  &  \\ 
  21 & Cluster 1 Postpeak & PRES & P & P & P & P & P &  \\ 
  22 &  & TEMP & P & P & P & P & P &  \\ 
  23 &  & HUM & P & P & P & F &  &  \\ 
  24 &  & WSPD & P & P & P & P & P &  \\ 
  25 &  & NO2 & P & P & P & F &  &  \\ 
  26 &  & O3 & P & P & F & F &  &  \\ 
  27 &  & PM2.5 & F & F & F & F &  &  \\ 
  28 &  & PM10 & F & F & F & F &  &  \\ 
  29 &  & SO2 & P & P & F & F &  &  \\ 
  30 &  & CO & P & P & F & F &  &  \\ 
  31 & Cluster 2 Overall & PRES & P & P & P & P & P &  \\ 
  32 &  & TEMP & P & P & P & P & P &  \\ 
  33 &  & HUM & P & P & F & F &  &  \\ 
  34 &  & WSPD & P & P & P & P & P &  \\ 
  35 &  & NO2 & P & P & P & P & P &  \\ 
  36 &  & O3 & P & P & F & F &  &  \\ 
  37 &  & PM2.5 & P & P & P & P & P &  \\ 
  38 &  & PM10 & P & P & P & P & P &  \\ 
  39 &  & SO2 & P & P & P & F &  &  \\ 
  40 &  & CO & P & P & F & F &  &  \\ 
  41 & Cluster 2 Spreading & PRES & P & P & F & F &  &  \\ 
  42 &  & TEMP & P & P & F & F &  &  \\ 
  43 &  & HUM & P & P & F & F &  &  \\ 
  44 &  & WSPD & P & P & P & P & P &  \\ 
  45 &  & NO2 & P & P & P & P & P &  \\ 
  46 &  & O3 & P & P & P & F &  &  \\ 
  47 &  & PM2.5 & P & P & P & P & P &  \\ 
  48 &  & PM10 & P & P & P & P & P &  \\ 
  49 &  & SO2 & P & P & P & P & P &  \\ 
  50 &  & CO & P & P & F & F &  &  \\ 
  51 & Cluster 2 Postpeak & PRES & P & P & P & P & P &  \\ 
  52 &  & TEMP & P & P & P & P & P &  \\ 
  53 &  & HUM & P & P & P & P & P &  \\ 
  54 &  & WSPD & P & P & P & P & P &  \\ 
  55 &  & NO2 & P & P & P & F &  &  \\ 
  56 &  & O3 & P & P & P & F &  &  \\ 
  57 &  & PM2.5 & P & P & P & P & P &  \\ 
  58 &  & PM10 & P & P & P & P & P &  \\ 
  59 &  & SO2 & P & P & P & P & P &  \\ 
  60 &  & CO & P & P & P & P & P &  \\ 
  61 & Cluster 3 Overall & PRES & P & P & P & P & P &  \\ 
  62 &  & TEMP & P & P & P & P & P &  \\ 
  63 &  & HUM & P & P & P & P & P &  \\ 
  64 &  & WSPD & P & P & P & P & P &  \\ 
  65 &  & NO2 & P & P & P & P & P &  \\ 
  66 &  & O3 & P & P & P & P & P &  \\ 
  67 &  & PM2.5 & P & P & P & P & P &  \\ 
  68 &  & PM10 & P & P & P & P & P &  \\ 
  69 &  & SO2 & P & P & P & F &  &  \\ 
  70 &  & CO & P & P & P & P & P &  \\ 
  71 & Cluster 3 Spreading & PRES & P & P & P & P & P &  \\ 
  72 &  & TEMP & P & P & P & P & P &  \\ 
  73 &  & HUM & P & P & P & P & P &  \\ 
  74 &  & WSPD & P & P & P & P & P &  \\ 
  75 &  & NO2 & P & P & P & F &  &  \\ 
  76 &  & O3 & P & P & P & F &  &  \\ 
  77 &  & PM2.5 & P & P & P & P & P &  \\ 
  78 &  & PM10 & P & P & P & P & P &  \\ 
  79 &  & SO2 & P & P & F & F &  &  \\ 
  80 &  & CO & P & P & P & F &  &  \\ 
  81 & Cluster 3 Postpeak & PRES & P & P & F & F &  &  \\ 
  82 &  & TEMP & P & F & F & F &  &  \\ 
  83 &  & HUM & P & F & F & F &  &  \\ 
  84 &  & WSPD & P & P & F & F &  &  \\ 
  85 &  & NO2 & P & F & F & F &  &  \\ 
  86 &  & O3 & F & F & F & F &  &  \\ 
  87 &  & PM2.5 & P & P & P & P & P &  \\ 
  88 &  & PM10 & P & P & P & F &  &  \\ 
  89 &  & SO2 & P & P & F & F &  &  \\ 
  90 &  & CO & P & P & P & P & P &  \\ 
   \hline
\end{tabular}%
}
   \caption{ATE and Random Common Cause Refutation Tests-Note: The first column represents the city clusters and their respective pandemic phases, while the second column represents the various features. The third through sixth column represents the refutation at the various levels, while the last column represents whether the given treatment has passed all the varying levels of refutation tests.}
\end{table}




\newpage 
\begin{thebibliography}{9}

\end{thebibliography}

\newpage 

# Code Appendix 

