--
title: "156 Replication Project"
author: "Samuel Gao"
date: "9/28/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(translateR)
```

The following code is what I used to clean and analyze the data.

```{r}
dat = read.csv("~/Documents/UC BERKELEY/STATISTICS/STAT 156/Final Project/GitHub/EnvCausal-replication/data/snapshot_data.csv")
```

The following are premininary summaries of the data.

```{r}
summary(dat)

dat = dat[-c(20:23)]
summary(dat)
```


```{r}
levels(dat$City) = c(levels(dat$City), "Xiamen", "Lhasa", "Urumqi", "Chongqing", "Hohhot", "Changsha", "Foshan", "Bengbu", "Luliang")
dat$City[9] = "Xiamen"
dat$City[14] = "Lasa"
dat$City[18] = "Wulumuqi"
dat$City[21] = "Chongqing"
dat$City[41] = "Luliang"
dat$City[75] = "Huhehaote"
dat$City[152] = "Changsha"
dat$City[161] = "Foshan"
dat$City[103] = "Bengbu"

```


First sanity check is to see if the GDP numbers add up. GDP values from the primary sector, secondary sector, and tetritary sectors should add up to the total value of the GDP. 

```{r}
filter(dat, abs(dat$PRIM + dat$SEC + dat$TERT - dat$GDP) >1)
```

```{r}
dat$SEC[dat$City == "Changchun"] = 2495.4
dat$GDP[dat$City == "Xiamen"] = 5995.04
dat$PRIM[dat$City == "Chongqing"] = 1551.42
dat$GDP[dat$City == "Baoding"] = 3558
dat$TERT[dat$City == "Huzhou"] = 1393.2

filter(dat, abs(dat$PRIM + dat$SEC + dat$TERT - dat$GDP) >1)

```

```{r}
dat$POP = dat$POP*10
dat$GDP = dat$GDP/6.91/10
dat$PRIM = dat$PRIM/6.91/10
dat$SEC = dat$SEC/6.91/10
dat$TERT = dat$TERT/6.91/10
dat$GDPpc = dat$GDP/dat$POP*1000
dat$Prim. = dat$PRIM/dat$GDP
dat$Sec.= dat$SEC/dat$GDP
dat$Tert. = dat$TERT/dat$GDP
dat$POPDENS = dat$POP/dat$Area*1000
dat$Prim. = dat$Prim.*100
dat$Sec.= dat$Sec. *100
dat$Tert.= dat$Tert. *100
dat$X.60yr. = dat$X.60yr.*100
dat$TVLR.= dat$TVLR.*1000
dat$TVLR = dat$TVLR*10
```

```{r}
summary(dat)
```

```{r}
write.csv(dat, "~/Documents/UC BERKELEY/STATISTICS/STAT 156/Final Project/GitHub/EnvCausal-replication/data/cleaned_data.csv")
```


```{r}
envdat_1 = read.csv("~/Documents/UC_BERKELEY/STATISTICS/STAT_156/Final_Project/EnvCausal-main/data/time_series/3_day_moving_average/df_m3.csv")

envdat = read.csv("~/Documents/UC BERKELEY/STATISTICS/STAT 156/Final Project/GitHub/EnvCausal-replication/data/envdat_translated.csv")

levels(envdat$City) = c(levels(envdat$City), "Suzhou_1", "Taizhou_1", "Xiamen", "Lhasa", "Urumqi", "Chongqing", "Hohhot", "Changsha", "Foshan", "Bengbu", "Luliang")

envdat$City[3901:3978] = "Suzhou_1"
envdat$City[11311:11388] = "Chongqing"
envdat$City[1951:2028] = "Xiamen"

envdat$days = c(rep(0:77, 166))
```

```{r}
summary(envdat)
```

```{r}
dat$GDPpc = dat$GDPpc*6.91

cluster1 = filter(dat, City == "Beijing" | City == "Shanghai" | City == "Chongqing" |City ==  "Suzhou" | City == "Chengdu" |City ==  "Guangzhou" | City ==  "Shenzhen")
cluster1 = cluster1[-5, ]

write.csv(cluster1, "~/Documents/UC BERKELEY/STATISTICS/STAT 156/Final Project/GitHub/EnvCausal-replication/data/cluster1.csv")

summary(cluster1)
```

```{r}
cluster2 = filter(dat, City == "Shenyang" | City == "Dalian" | City == "Fuzhou" |City ==  "Xiamen" | City == "Nanning" |City ==  "Haikou" | City ==  "Guiyang" | City == "Kunming" | City == "Lasa" |
 City == "Lanzhou" |City ==  "Xining" | City ==  "Yinchuan" | City == "Wulumuqi" | City == "Tianjin" | City == "Shijiazhuang" |    City == "Taiyuan" |City ==  "Jinan" | City ==  "Qingdao" | City == "Zhengzhou" | City == "Huhehaote" |    City == "Baotou" |City ==  "Nanjing" | City ==  "Wuxi" | City == "Changzhou" | City == "Hangzhou" |     City == "Ningbo" |City ==  "Wenzhou" | City ==  "Shaoxing" | City == "Jiaxing" | City == "Jinhua" |     City == "Hefei" |City ==  "Xian" | City ==  "Tongchuan" | City == "Nanchang" | City == "Changsha" |
City == "Zhuhai" |City ==  "Foshan" | City ==  "Huizhou" | City == "Dongguan" | City == "Zhongshan")
 
write.csv(cluster2, "~/Documents/UC BERKELEY/STATISTICS/STAT 156/Final Project/GitHub/EnvCausal-replication/data/cluster2.csv") 

summary(cluster2)
  
```

```{r}
cluster3 = dat[-c(1, 2, 8:23, 34, 45, 46, 58, 75:78, 80, 81, 90:93, 95, 96, 101, 117, 120, 122, 147, 152, 158, 159, 160, 161, 165, 164, 166), ]

write.csv(cluster3, "~/Documents/UC BERKELEY/STATISTICS/STAT 156/Final Project/GitHub/EnvCausal-replication/data/cluster3.csv") 

summary(cluster3)
```

```{r}
write.csv(envdat_1, "~/Documents/UC BERKELEY/STATISTICS/STAT 156/Final Project/GitHub/EnvCausal-replication/data/envdat.csv") 

write.csv(envdat, "~/Documents/UC BERKELEY/STATISTICS/STAT 156/Final Project/GitHub/EnvCausal-replication/data/envdat_translated.csv") 

```

```{r}
time_cluster_1 = envdat[envdat$City== "Shanghai", ]
time_cluster_1 = rbind(time_cluster_1, envdat[envdat$City== "Chongqing", ])
time_cluster_1 = rbind(time_cluster_1, envdat[envdat$City== "Suzhou", ])
time_cluster_1 = rbind(time_cluster_1, envdat[envdat$City== "Beijing", ])
time_cluster_1 = rbind(time_cluster_1, envdat[envdat$City== "Chengdu", ])
time_cluster_1 = rbind(time_cluster_1, envdat[envdat$City== "Guangzhou", ])
time_cluster_1 = rbind(time_cluster_1, envdat[envdat$City== "Shenzhen", ])
```

```{r}
time_cluster_2 = envdat[envdat$City== "Shenyang", ]
time_cluster_2 = rbind(time_cluster_2, envdat[envdat$City== "Dalian", ])
time_cluster_2 = rbind(time_cluster_2, envdat[envdat$City== "Fuzhou", ])
time_cluster_2 = rbind(time_cluster_2, envdat[envdat$City== "Xiamen", ])
time_cluster_2 = rbind(time_cluster_2, envdat[envdat$City== "Nanning", ])
time_cluster_2 = rbind(time_cluster_2, envdat[envdat$City== "Haikou", ])
time_cluster_2 = rbind(time_cluster_2, envdat[envdat$City== "Guiyang", ])
time_cluster_2 = rbind(time_cluster_2, envdat[envdat$City== "Kunming", ])
time_cluster_2 = rbind(time_cluster_2, envdat[envdat$City== "Lasa", ])
time_cluster_2 = rbind(time_cluster_2, envdat[envdat$City== "Lanzhou", ])
time_cluster_2 = rbind(time_cluster_2, envdat[envdat$City== "Xining", ])
time_cluster_2 = rbind(time_cluster_2, envdat[envdat$City== "Yinchuan", ])
time_cluster_2 = rbind(time_cluster_2, envdat[envdat$City== "Wulumuqi", ])
time_cluster_2 = rbind(time_cluster_2, envdat[envdat$City== "Tianjin", ])
time_cluster_2 = rbind(time_cluster_2, envdat[envdat$City== "Shijiazhuang", ])
time_cluster_2 = rbind(time_cluster_2, envdat[envdat$City== "Taiyuan", ])
time_cluster_2 = rbind(time_cluster_2, envdat[envdat$City== "Jinan", ])
time_cluster_2 = rbind(time_cluster_2, envdat[envdat$City== "Qingdao", ])
time_cluster_2 = rbind(time_cluster_2, envdat[envdat$City== "Zhengzhou", ])
time_cluster_2 = rbind(time_cluster_2, envdat[envdat$City== "Huhehaote", ])
time_cluster_2 = rbind(time_cluster_2, envdat[envdat$City== "Baotou", ])
time_cluster_2 = rbind(time_cluster_2, envdat[envdat$City== "Nanjing", ])
time_cluster_2 = rbind(time_cluster_2, envdat[envdat$City== "Wuxi", ])
time_cluster_2 = rbind(time_cluster_2, envdat[envdat$City== "Changzhou", ])
time_cluster_2 = rbind(time_cluster_2, envdat[envdat$City== "Hangzhou", ])
time_cluster_2 = rbind(time_cluster_2, envdat[envdat$City== "Ningbo", ])
time_cluster_2 = rbind(time_cluster_2, envdat[envdat$City== "Wenzhou", ])
time_cluster_2 = rbind(time_cluster_2, envdat[envdat$City== "Shaoxing", ])
time_cluster_2 = rbind(time_cluster_2, envdat[envdat$City== "Jinhua", ])
time_cluster_2 = rbind(time_cluster_2, envdat[envdat$City== "Jiaxing", ])
time_cluster_2 = rbind(time_cluster_2, envdat[envdat$City== "Hefei", ])
time_cluster_2 = rbind(time_cluster_2, envdat[envdat$City== "Xian", ])
time_cluster_2 = rbind(time_cluster_2, envdat[envdat$City== "Tongchuan", ])
time_cluster_2 = rbind(time_cluster_2, envdat[envdat$City== "Nanchang", ])
time_cluster_2 = rbind(time_cluster_2, envdat[envdat$City== "Changsha", ])
time_cluster_2 = rbind(time_cluster_2, envdat[envdat$City== "Zhuhai", ])
time_cluster_2 = rbind(time_cluster_2, envdat[envdat$City== "Foshan", ])
time_cluster_2 = rbind(time_cluster_2, envdat[envdat$City== "Huizhou", ])
time_cluster_2 = rbind(time_cluster_2, envdat[envdat$City== "Dongguan", ])
time_cluster_2 = rbind(time_cluster_2, envdat[envdat$City== "Zhongshan", ])
```

```{r}
time_cluster_3 = envdat
time_cluster_3 = time_cluster_3[! time_cluster_3$City== "Shenyang", ]
time_cluster_3 = time_cluster_3[! time_cluster_3$City== "Dalian", ]
time_cluster_3 = time_cluster_3[! time_cluster_3$City== "Fuzhou", ]
time_cluster_3 = time_cluster_3[! time_cluster_3$City== "Xiamen", ]
time_cluster_3 = time_cluster_3[! time_cluster_3$City== "Nanning", ]
time_cluster_3 = time_cluster_3[! time_cluster_3$City== "Haikou", ]
time_cluster_3 = time_cluster_3[! time_cluster_3$City== "Guiyang", ]
time_cluster_3 = time_cluster_3[! time_cluster_3$City== "Kunming", ]
time_cluster_3 = time_cluster_3[! time_cluster_3$City== "Lasa", ]
time_cluster_3 = time_cluster_3[! time_cluster_3$City== "Lanzhou", ]
time_cluster_3 = time_cluster_3[! time_cluster_3$City== "Xining", ]
time_cluster_3 = time_cluster_3[! time_cluster_3$City== "Yinchuan", ]
time_cluster_3 = time_cluster_3[! time_cluster_3$City== "Wulumuqi", ]
time_cluster_3 = time_cluster_3[! time_cluster_3$City== "Tianjin", ]
time_cluster_3 = time_cluster_3[! time_cluster_3$City== "Shijiazhuang", ]
time_cluster_3 = time_cluster_3[! time_cluster_3$City== "Taiyuan", ]
time_cluster_3 = time_cluster_3[! time_cluster_3$City== "Jinan", ]
time_cluster_3 = time_cluster_3[! time_cluster_3$City== "Qingdao", ]
time_cluster_3 = time_cluster_3[! time_cluster_3$City== "Zhengzhou", ]
time_cluster_3 = time_cluster_3[! time_cluster_3$City== "Huhehaote", ]
time_cluster_3 = time_cluster_3[! time_cluster_3$City== "Baotou", ]
time_cluster_3 = time_cluster_3[! time_cluster_3$City== "Nanjing", ]
time_cluster_3 = time_cluster_3[! time_cluster_3$City== "Wuxi", ]
time_cluster_3 = time_cluster_3[! time_cluster_3$City== "Changzhou", ]
time_cluster_3 = time_cluster_3[! time_cluster_3$City== "Hangzhou", ]
time_cluster_3 = time_cluster_3[! time_cluster_3$City== "Ningbo", ]
time_cluster_3 = time_cluster_3[! time_cluster_3$City== "Wenzhou", ]
time_cluster_3 = time_cluster_3[! time_cluster_3$City== "Shaoxing", ]
time_cluster_3 = time_cluster_3[! time_cluster_3$City== "Jinhua", ]
time_cluster_3 = time_cluster_3[! time_cluster_3$City== "Jiaxing", ]
time_cluster_3 = time_cluster_3[! time_cluster_3$City== "Hefei", ]
time_cluster_3 = time_cluster_3[! time_cluster_3$City== "Xian", ]
time_cluster_3 = time_cluster_3[! time_cluster_3$City== "Tongchuan", ]
time_cluster_3 = time_cluster_3[! time_cluster_3$City== "Nanchang", ]
time_cluster_3 = time_cluster_3[! time_cluster_3$City== "Changsha", ]
time_cluster_3 = time_cluster_3[! time_cluster_3$City== "Zhuhai", ]
time_cluster_3 = time_cluster_3[! time_cluster_3$City== "Foshan", ]
time_cluster_3 = time_cluster_3[! time_cluster_3$City== "Huizhou", ]
time_cluster_3 = time_cluster_3[! time_cluster_3$City== "Dongguan", ]
time_cluster_3 = time_cluster_3[! time_cluster_3$City== "Zhongshan", ]
time_cluster_3 = time_cluster_3[! time_cluster_3$City== "Chongqing", ]
time_cluster_3 = time_cluster_3[! time_cluster_3$City== "Suzhou", ]
time_cluster_3 = time_cluster_3[! time_cluster_3$City== "Beijing", ]
time_cluster_3 = time_cluster_3[! time_cluster_3$City== "Chengdu", ]
time_cluster_3 = time_cluster_3[! time_cluster_3$City== "Guangzhou", ]
time_cluster_3 = time_cluster_3[! time_cluster_3$City== "Shenzhen", ]
time_cluster_3 = time_cluster_3[! time_cluster_3$City== "Shanghai", ]
time_cluster_3$City[time_cluster_3$City == "Suzhou_1"] = "Suzhou"
```

```{r}
time_cluster_1_spread = time_cluster_1[time_cluster_1$X == "2020-01-22", ]
time_cluster_1_spread = rbind(time_cluster_1_spread, time_cluster_1[time_cluster_1$X == "2020-01-23", ])
time_cluster_1_spread = rbind(time_cluster_1_spread, time_cluster_1[time_cluster_1$X == "2020-01-24", ])
time_cluster_1_spread = rbind(time_cluster_1_spread, time_cluster_1[time_cluster_1$X == "2020-01-25", ])
time_cluster_1_spread = rbind(time_cluster_1_spread, time_cluster_1[time_cluster_1$X == "2020-01-26", ])
time_cluster_1_spread = rbind(time_cluster_1_spread, time_cluster_1[time_cluster_1$X == "2020-01-27", ])
time_cluster_1_spread = rbind(time_cluster_1_spread, time_cluster_1[time_cluster_1$X == "2020-01-28", ])
time_cluster_1_spread = rbind(time_cluster_1_spread, time_cluster_1[time_cluster_1$X == "2020-01-29", ])
time_cluster_1_spread = rbind(time_cluster_1_spread, time_cluster_1[time_cluster_1$X == "2020-01-30", ])
time_cluster_1_spread = rbind(time_cluster_1_spread, time_cluster_1[time_cluster_1$X == "2020-01-31", ])
time_cluster_1_spread = rbind(time_cluster_1_spread, time_cluster_1[time_cluster_1$X == "2020-02-01", ])
time_cluster_1_spread = rbind(time_cluster_1_spread, time_cluster_1[time_cluster_1$X == "2020-02-02", ])
time_cluster_1_spread = rbind(time_cluster_1_spread, time_cluster_1[time_cluster_1$X == "2020-02-03", ])
```

```{r}
time_cluster_1_postpeak = time_cluster_1
time_cluster_1_postpeak = time_cluster_1_postpeak[ ! time_cluster_1_postpeak$X == "2020-01-22", ]
time_cluster_1_postpeak = time_cluster_1_postpeak[ ! time_cluster_1_postpeak$X == "2020-01-23", ]
time_cluster_1_postpeak = time_cluster_1_postpeak[ ! time_cluster_1_postpeak$X == "2020-01-24", ]
time_cluster_1_postpeak = time_cluster_1_postpeak[ ! time_cluster_1_postpeak$X == "2020-01-25", ]
time_cluster_1_postpeak = time_cluster_1_postpeak[ ! time_cluster_1_postpeak$X == "2020-01-26", ]
time_cluster_1_postpeak = time_cluster_1_postpeak[ ! time_cluster_1_postpeak$X == "2020-01-27", ]
time_cluster_1_postpeak = time_cluster_1_postpeak[ ! time_cluster_1_postpeak$X == "2020-01-28", ]
time_cluster_1_postpeak = time_cluster_1_postpeak[ ! time_cluster_1_postpeak$X == "2020-01-29", ]
time_cluster_1_postpeak = time_cluster_1_postpeak[ ! time_cluster_1_postpeak$X == "2020-01-30", ]
time_cluster_1_postpeak = time_cluster_1_postpeak[ ! time_cluster_1_postpeak$X == "2020-01-31", ]
time_cluster_1_postpeak = time_cluster_1_postpeak[ ! time_cluster_1_postpeak$X == "2020-02-01", ]
time_cluster_1_postpeak = time_cluster_1_postpeak[ ! time_cluster_1_postpeak$X == "2020-02-02", ]
time_cluster_1_postpeak = time_cluster_1_postpeak[ ! time_cluster_1_postpeak$X == "2020-02-03", ]
```


```{r}
time_cluster_2_spread = time_cluster_2[time_cluster_2$X == "2020-01-22", ]
time_cluster_2_spread = rbind(time_cluster_2_spread, time_cluster_2[time_cluster_2$X == "2020-01-23", ])
time_cluster_2_spread = rbind(time_cluster_2_spread, time_cluster_2[time_cluster_2$X == "2020-01-24", ])
time_cluster_2_spread = rbind(time_cluster_2_spread, time_cluster_2[time_cluster_2$X == "2020-01-25", ])
time_cluster_2_spread = rbind(time_cluster_2_spread, time_cluster_2[time_cluster_2$X == "2020-01-26", ])
time_cluster_2_spread = rbind(time_cluster_2_spread, time_cluster_2[time_cluster_2$X == "2020-01-27", ])
time_cluster_2_spread = rbind(time_cluster_2_spread, time_cluster_2[time_cluster_2$X == "2020-01-28", ])
time_cluster_2_spread = rbind(time_cluster_2_spread, time_cluster_2[time_cluster_2$X == "2020-01-29", ])
time_cluster_2_spread = rbind(time_cluster_2_spread, time_cluster_2[time_cluster_2$X == "2020-01-30", ])
time_cluster_2_spread = rbind(time_cluster_2_spread, time_cluster_2[time_cluster_2$X == "2020-01-31", ])
time_cluster_2_spread = rbind(time_cluster_2_spread, time_cluster_2[time_cluster_2$X == "2020-02-01", ])
time_cluster_2_spread = rbind(time_cluster_2_spread, time_cluster_2[time_cluster_2$X == "2020-02-02", ])
time_cluster_2_spread = rbind(time_cluster_2_spread, time_cluster_2[time_cluster_2$X == "2020-02-03", ])
time_cluster_2_spread = rbind(time_cluster_2_spread, time_cluster_2[time_cluster_2$X == "2020-02-04", ])
time_cluster_2_spread = rbind(time_cluster_2_spread, time_cluster_2[time_cluster_2$X == "2020-02-05", ])
time_cluster_2_spread = rbind(time_cluster_2_spread, time_cluster_2[time_cluster_2$X == "2020-02-06", ])
```

```{r}
time_cluster_2_postpeak = time_cluster_2
time_cluster_2_postpeak = time_cluster_2_postpeak[ ! time_cluster_2_postpeak$X == "2020-01-22", ]
time_cluster_2_postpeak = time_cluster_2_postpeak[ ! time_cluster_2_postpeak$X == "2020-01-23", ]
time_cluster_2_postpeak = time_cluster_2_postpeak[ ! time_cluster_2_postpeak$X == "2020-01-24", ]
time_cluster_2_postpeak = time_cluster_2_postpeak[ ! time_cluster_2_postpeak$X == "2020-01-25", ]
time_cluster_2_postpeak = time_cluster_2_postpeak[ ! time_cluster_2_postpeak$X == "2020-01-26", ]
time_cluster_2_postpeak = time_cluster_2_postpeak[ ! time_cluster_2_postpeak$X == "2020-01-27", ]
time_cluster_2_postpeak = time_cluster_2_postpeak[ ! time_cluster_2_postpeak$X == "2020-01-28", ]
time_cluster_2_postpeak = time_cluster_2_postpeak[ ! time_cluster_2_postpeak$X == "2020-01-29", ]
time_cluster_2_postpeak = time_cluster_2_postpeak[ ! time_cluster_2_postpeak$X == "2020-01-30", ]
time_cluster_2_postpeak = time_cluster_2_postpeak[ ! time_cluster_2_postpeak$X == "2020-01-31", ]
time_cluster_2_postpeak = time_cluster_2_postpeak[ ! time_cluster_2_postpeak$X == "2020-02-01", ]
time_cluster_2_postpeak = time_cluster_2_postpeak[ ! time_cluster_2_postpeak$X == "2020-02-02", ]
time_cluster_2_postpeak = time_cluster_2_postpeak[ ! time_cluster_2_postpeak$X == "2020-02-03", ]
time_cluster_2_postpeak = time_cluster_2_postpeak[ ! time_cluster_2_postpeak$X == "2020-02-04", ]
time_cluster_2_postpeak = time_cluster_2_postpeak[ ! time_cluster_2_postpeak$X == "2020-02-05", ]
time_cluster_2_postpeak = time_cluster_2_postpeak[ ! time_cluster_2_postpeak$X == "2020-02-06", ]
```

```{r}
time_cluster_3_spread = time_cluster_3[time_cluster_3$X == "2020-01-22", ]
time_cluster_3_spread = rbind(time_cluster_3_spread, time_cluster_3[time_cluster_3$X == "2020-01-23", ])
time_cluster_3_spread = rbind(time_cluster_3_spread, time_cluster_3[time_cluster_3$X == "2020-01-24", ])
time_cluster_3_spread = rbind(time_cluster_3_spread, time_cluster_3[time_cluster_3$X == "2020-01-25", ])
time_cluster_3_spread = rbind(time_cluster_3_spread, time_cluster_3[time_cluster_3$X == "2020-01-26", ])
time_cluster_3_spread = rbind(time_cluster_3_spread, time_cluster_3[time_cluster_3$X == "2020-01-27", ])
time_cluster_3_spread = rbind(time_cluster_3_spread, time_cluster_3[time_cluster_3$X == "2020-01-28", ])
time_cluster_3_spread = rbind(time_cluster_3_spread, time_cluster_3[time_cluster_3$X == "2020-01-29", ])
time_cluster_3_spread = rbind(time_cluster_3_spread, time_cluster_3[time_cluster_3$X == "2020-01-30", ])
time_cluster_3_spread = rbind(time_cluster_3_spread, time_cluster_3[time_cluster_3$X == "2020-01-31", ])
time_cluster_3_spread = rbind(time_cluster_3_spread, time_cluster_3[time_cluster_3$X == "2020-02-01", ])
time_cluster_3_spread = rbind(time_cluster_3_spread, time_cluster_3[time_cluster_3$X == "2020-02-02", ])
time_cluster_3_spread = rbind(time_cluster_3_spread, time_cluster_3[time_cluster_3$X == "2020-02-03", ])
time_cluster_3_spread = rbind(time_cluster_3_spread, time_cluster_3[time_cluster_3$X == "2020-02-04", ])
time_cluster_3_spread = rbind(time_cluster_3_spread, time_cluster_3[time_cluster_3$X == "2020-02-05", ])
time_cluster_3_spread = rbind(time_cluster_3_spread, time_cluster_3[time_cluster_3$X == "2020-02-06", ])
```

```{r}
time_cluster_3_postpeak = time_cluster_3
time_cluster_3_postpeak = time_cluster_3_postpeak[ ! time_cluster_3_postpeak$X == "2020-01-22", ]
time_cluster_3_postpeak = time_cluster_3_postpeak[ ! time_cluster_3_postpeak$X == "2020-01-23", ]
time_cluster_3_postpeak = time_cluster_3_postpeak[ ! time_cluster_3_postpeak$X == "2020-01-24", ]
time_cluster_3_postpeak = time_cluster_3_postpeak[ ! time_cluster_3_postpeak$X == "2020-01-25", ]
time_cluster_3_postpeak = time_cluster_3_postpeak[ ! time_cluster_3_postpeak$X == "2020-01-26", ]
time_cluster_3_postpeak = time_cluster_3_postpeak[ ! time_cluster_3_postpeak$X == "2020-01-27", ]
time_cluster_3_postpeak = time_cluster_3_postpeak[ ! time_cluster_3_postpeak$X == "2020-01-28", ]
time_cluster_3_postpeak = time_cluster_3_postpeak[ ! time_cluster_3_postpeak$X == "2020-01-29", ]
time_cluster_3_postpeak = time_cluster_3_postpeak[ ! time_cluster_3_postpeak$X == "2020-01-30", ]
time_cluster_3_postpeak = time_cluster_3_postpeak[ ! time_cluster_3_postpeak$X == "2020-01-31", ]
time_cluster_3_postpeak = time_cluster_3_postpeak[ ! time_cluster_3_postpeak$X == "2020-02-01", ]
time_cluster_3_postpeak = time_cluster_3_postpeak[ ! time_cluster_3_postpeak$X == "2020-02-02", ]
time_cluster_3_postpeak = time_cluster_3_postpeak[ ! time_cluster_3_postpeak$X == "2020-02-03", ]
time_cluster_3_postpeak = time_cluster_3_postpeak[ ! time_cluster_3_postpeak$X == "2020-02-04", ]
time_cluster_3_postpeak = time_cluster_3_postpeak[ ! time_cluster_3_postpeak$X == "2020-02-05", ]
time_cluster_3_postpeak = time_cluster_3_postpeak[ ! time_cluster_3_postpeak$X == "2020-02-06", ]
```


```{r}
write.csv(time_cluster_1, "~/Documents/UC BERKELEY/STATISTICS/STAT 156/Final Project/GitHub/EnvCausal-replication/data/time_cluster_1.csv") 
write.csv(time_cluster_1_postpeak, "~/Documents/UC BERKELEY/STATISTICS/STAT 156/Final Project/GitHub/EnvCausal-replication/data/time_cluster_1_postpeak.csv") 
write.csv(time_cluster_1_spread, "~/Documents/UC BERKELEY/STATISTICS/STAT 156/Final Project/GitHub/EnvCausal-replication/data/time_cluster_1_spread.csv") 

write.csv(time_cluster_2, "~/Documents/UC BERKELEY/STATISTICS/STAT 156/Final Project/GitHub/EnvCausal-replication/data/time_cluster_2.csv") 
write.csv(time_cluster_2_postpeak, "~/Documents/UC BERKELEY/STATISTICS/STAT 156/Final Project/GitHub/EnvCausal-replication/data/time_cluster_2_postpeak.csv") 
write.csv(time_cluster_2_spread, "~/Documents/UC BERKELEY/STATISTICS/STAT 156/Final Project/GitHub/EnvCausal-replication/data/time_cluster_2_spread.csv") 

write.csv(time_cluster_3, "~/Documents/UC BERKELEY/STATISTICS/STAT 156/Final Project/GitHub/EnvCausal-replication/data/time_cluster_3.csv") 
write.csv(time_cluster_3_postpeak, "~/Documents/UC BERKELEY/STATISTICS/STAT 156/Final Project/GitHub/EnvCausal-replication/data/time_cluster_3_postpeak.csv") 
write.csv(time_cluster_3_spread, "~/Documents/UC BERKELEY/STATISTICS/STAT 156/Final Project/GitHub/EnvCausal-replication/data/time_cluster_3_spread.csv") 

write.csv(cities, "~/Documents/UC BERKELEY/STATISTICS/STAT 156/Final Project/GitHub/EnvCausal-replication/data/cities.csv") 

```


